os: linux
dist: xenial
language: node_js
node_js:
    - 13
before_install:
    - npm i -g npm
branches:
    only:
        - master
        - dev
        - travis
cache:
    npm: false
after_success:
    - bash ./push.sh