name: 'Auto Assign'
on: pull_request

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          addReviewers: true
          addAssignees: true
          reviewers: keanuplayz
          assignees: keanuplayz
          numberOfReviewers: 0
